# nginx-deploy.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: label-nginx-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: label-nginx-deploy
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.24
